backend:
  name: github
  repo: uptheirons78/museo-civico-nepi
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/assets
public_folder: /assets

collections:
  # Blog Post Types
  # Monumenti
  - name: "monumenti"
    label: "Monumenti"
    folder: "content/monuments"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
     preview: false
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "monumenti"}
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Data di pubblicazione", name: "date", widget: "datetime" }
      - { label: "Descrizione", name: "description", widget: "string" }
      - { label: "Categoria",
          name: "category",
          widget: "string",
          default: "monumenti"
        }
      - {label: "In Evidenza", name: "featured", widget: "boolean", default: false}
      - { label: "Thumbnail",
          name: "image",
          widget: "image"
        }
      - { label: "Indirizzo", name: "place", widget: "string" }
      - { label: "Orario", name: "access", widget: "string" }
      - { label: "Info Biglietti", name: "ticket", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Gallery",
          name: "gallery",
          widget: "list",
          fields:
            [
              { label: "Foto", name: "image", widget: "image" },
              { label: "Descrizione Foto", name: "alt", widget: "string" },
            ],
        }
  # Monuments (English)
  - name: "monuments"
    label: "Monuments"
    folder: "content/en-monuments"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
     preview: false
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "monuments"}
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Published", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Category",
          name: "category",
          widget: "string",
          default: "monumenti"
        }
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - { label: "Thumbnail",
          name: "image",
          widget: "image"
        }
      - { label: "Address", name: "place", widget: "string" }
      - { label: "Opening", name: "access", widget: "string" }
      - { label: "Tickets", name: "ticket", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Gallery",
          name: "gallery",
          widget: "list",
          fields:
            [
              { label: "Image", name: "image", widget: "image" },
              { label: "Image Description", name: "alt", widget: "string" },
            ],
        }
  # Eventi (Italiano)
  - name: "eventi"
    label: "Eventi"
    folder: "content/events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
     preview: false
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "eventi"}
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Data di pubblicazione", name: "date", widget: "datetime" }
      - { label: "Data di inizio evento", name: "start", widget: "datetime" }
      - { label: "Data di fine evento", name: "end", widget: "datetime" }
      - { label: "Descrizione", name: "description", widget: "string" }
      - { label: "Categoria",
          name: "category",
          widget: "string",
          default: "eventi"
        }
      - {label: "In Evidenza", name: "featured", widget: "boolean", default: false}
      - { label: "Thumbnail",
          name: "image",
          widget: "image"
        }
      - { label: "Luogo Evento", name: "place", widget: "string" }
      - { label: "Orario", name: "access", widget: "string" }
      - { label: "Info Biglietti", name: "ticket", widget: "string" }
      - { label: "Tipologia Evento", name: "type", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Gallery",
          name: "gallery",
          widget: "list",
          fields:
            [
              { label: "Foto", name: "image", widget: "image" },
              { label: "Descrizione Foto", name: "alt", widget: "string" },
            ],
        }
  # Events (English)
  - name: "events"
    label: "Events"
    folder: "content/en-events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
     preview: false
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "events"}
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Published", name: "date", widget: "datetime" }
      - { label: "Starting Date", name: "start", widget: "datetime" }
      - { label: "Ending Date", name: "end", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Category",
          name: "category",
          widget: "string",
          default: "eventi"
        }
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - { label: "Thumbnail",
          name: "image",
          widget: "image"
        }
      - { label: "Place", name: "place", widget: "string" }
      - { label: "Opening", name: "access", widget: "string" }
      - { label: "Tickets", name: "ticket", widget: "string" }
      - { label: "Event Type", name: "type", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Gallery",
          name: "gallery",
          widget: "list",
          fields:
            [
              { label: "Image", name: "image", widget: "image" },
              { label: "Image Description", name: "alt", widget: "string" },
            ],
        }
  # Pages
  - name: "pages"
    label: "Pages"
    files:
      # Museum Page
      - file: "content/pages/museum/index.md"
        label: "Museo"
        name: "museum"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "museum"}
          - {label: Titolo, name: title, widget: string}
          - {
              label: "Italiano",
              name: "it",
              widget: "object",
              fields:
                [
                  {label: "Titolo", name: "title", widget: "string"},
                  {label: "Descrizione", name: "description", widget: "string"},
                  {label: "Text A", name: "textA", widget: "string"},
                  {label: "Text B", name: "textB", widget: "string"},
                  {label: "Text C", name: "textC", widget: "string"},
                ],
            }
          - {
              label: "English",
              name: "en",
              widget: "object",
              fields:
                [
                  {label: "Title", name: "title", widget: "string"},
                  {label: "Description", name: "description", widget: "string"},
                  {label: "Text A", name: "textA", widget: "string"},
                  {label: "Text B", name: "textB", widget: "string"},
                  {label: "Text C", name: "textC", widget: "string"},
                ],
            }
      # Mission Page
      - file: "content/pages/mission/index.md"
        label: "Mission"
        name: "mission"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "mission"}
          - {
              label: "Italiano",
              name: "it",
              widget: "object",
              fields:
                [
                  {label: "Titolo Pagina", name: "pageTitle", widget: "string"},
                  {label: "Descrizione Pagina", name: "pageDescription", widget: "string"},
                  {label: "Blocco di testo 1", name: "descriptionA", widget: "string"},
                  {label: "Blocco di testo 2", name: "descriptionB", widget: "string"},
                ],
            }
          - {
              label: "English",
              name: "en",
              widget: "object",
              fields:
                [
                  {label: "Page Title", name: "pageTitle", widget: "string"},
                  {label: "Page Description", name: "pageDescription", widget: "string"},
                  {label: "Text Block 1", name: "descriptionA", widget: "string"},
                  {label: "Text Block 2", name: "descriptionB", widget: "string"},
                ],
            }
      # Collections Page
      - file: "content/pages/collezioni/index.md"
        label: "Collezioni"
        name: "collezioni"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "collections"}
          - {
              label: "Italiano",
              name: "it",
              widget: "object",
              fields:
                [
                  {label: "Titolo Pagina", name: "pageTitle", widget: "string"},
                  {label: "Descrizione Pagina", name: "pageDescription", widget: "string"},
                  {label: "Titolo Blocco 1", name: "sectionATitle", widget: "string"},
                  {label: "Blocco di testo 1", name: "sectionA", widget: "string"},
                  {label: "Titolo Blocco 2", name: "sectionBTitle", widget: "string"},
                  {label: "Blocco di testo 2", name: "sectionB", widget: "string"},
                  {label: "Titolo Blocco 3", name: "sectionCTitle", widget: "string"},
                  {label: "Blocco di testo 3", name: "sectionC", widget: "string"},
                ],
            }
          - {
              label: "English",
              name: "en",
              widget: "object",
              fields:
                [
                  {label: "Page Title", name: "pageTitle", widget: "string"},
                  {label: "Page Description", name: "pageDescription", widget: "string"},
                  {label: "Block 1 Title", name: "sectionATitle", widget: "string"},
                  {label: "Block 1 Text", name: "sectionA", widget: "string"},
                  {label: "Block 2 Title", name: "sectionBTitle", widget: "string"},
                  {label: "Block 2 Text", name: "sectionB", widget: "string"},
                  {label: "Block 3 Title", name: "sectionCTitle", widget: "string"},
                  {label: "Block 3 Text", name: "sectionC", widget: "string"},
                ],
            }
      # Informations and Tickets Page
      - file: "content/pages/info/index.md"
        label: "Informazioni e Biglietti"
        name: "info"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "info"}
          - {
              label: "Italiano",
              name: "it",
              widget: "object",
              fields:
                [
                  {label: "Titolo Pagina", name: "pageTitle", widget: "string"},
                  {label: "Descrizione Pagina", name: "pageDescription", widget: "string"},
                  {label: "Titolo Blocco 1", name: "sectionATitle", widget: "string"},
                  {label: "Apertura Invernale", name: "winterOpening", widget: "string"},
                  {label: "Giorni Feriali Invernali", name: "winterTueFri", widget: "string"},
                  {label: "Giorni Festivi Invernali", name: "winterSatSun", widget: "string"},
                  {label: "Chiusura Invernale", name: "winterClosing", widget: "string"},
                  {label: "Apertura Estiva", name: "summerOpening", widget: "string"},
                  {label: "Giorni Feriali Estivi", name: "summerTueFri", widget: "string"},
                  {label: "Giorni Festivi Estivi", name: "summerSatSun", widget: "string"},
                  {label: "Chiusura Estiva", name: "summerClosing", widget: "string"},
                  {label: "Titolo Blocco 2", name: "sectionBTitle", widget: "string"},
                  {label: "Sempre Chiuso 1", name: "close1", widget: "string"},
                  {label: "Sempre Chiuso 2", name: "close2", widget: "string"},
                  {label: "Titolo Blocco 3", name: "sectionCTitle", widget: "string"},
                  {label: "Prezzo", name: "entrance", widget: "string"},
                ],
            }
          - {
              label: "English",
              name: "en",
              widget: "object",
              fields:
                [
                  {label: "Page Title", name: "pageTitle", widget: "string"},
                  {label: "Page Description", name: "pageDescription", widget: "string"},
                  {label: "Block 1 Title", name: "sectionATitle", widget: "string"},
                  {label: "Winter Openings", name: "winterOpening", widget: "string"},
                  {label: "Winter Working Days Openings", name: "winterTueFri", widget: "string"},
                  {label: "Winter Bank Holidays Openings", name: "winterSatSun", widget: "string"},
                  {label: "Winter Closing Day", name: "winterClosing", widget: "string"},
                  {label: "Summer Openings", name: "summerOpening", widget: "string"},
                  {label: "Summer Working Days Openings", name: "summerTueFri", widget: "string"},
                  {label: "Summerc Bank Holidays Openings", name: "summerSatSun", widget: "string"},
                  {label: "Summer Closing", name: "summerClosing", widget: "string"},
                  {label: "Block 2 Title", name: "sectionBTitle", widget: "string"},
                  {label: "Yearly Closing Days 1", name: "close1", widget: "string"},
                  {label: "Yearly Closing Days 2", name: "close2", widget: "string"},
                  {label: "Block 3 Title", name: "sectionCTitle", widget: "string"},
                  {label: "Prices", name: "entrance", widget: "string"},
                ],
            }
      # Contact Page
      - file: "content/pages/contact/index.md"
        label: "Contatti"
        name: "contact"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact"}
          - {
              label: "Italiano",
              name: "it",
              widget: "object",
              fields:
                [
                  {label: "Titolo Pagina", name: "pageTitle", widget: "string"},
                  {label: "Descrizione Pagina", name: "pageDescription", widget: "string"},
                  {label: "Titolo", name: "title", widget: "string"},
                  {label: "Descrizione", name: "description", widget: "string"},
                  {label: "Indirizzo", name: "address", widget: "string"},
                  {label: "Città", name: "city", widget: "string"},
                  {label: "Cap", name: "cap", widget: "string"},
                  {label: "Telefono", name: "telephone", widget: "string"},
                  {label: "Email", name: "email", widget: "string"},
                ],
            }
          - {
              label: "English",
              name: "en",
              widget: "object",
              fields:
                [
                  {label: "Page Title", name: "pageTitle", widget: "string"},
                  {label: "Page Description", name: "pageDescription", widget: "string"},
                  {label: "Title", name: "title", widget: "string"},
                  {label: "Description", name: "description", widget: "string"},
                  {label: "Address", name: "address", widget: "string"},
                  {label: "City", name: "city", widget: "string"},
                  {label: "Cap", name: "cap", widget: "string"},
                  {label: "Telephone", name: "telephone", widget: "string"},
                  {label: "Email", name: "email", widget: "string"},
                ],
            }