backend:
  name: github
  repo: uptheirons78/museo-civico-nepi
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/assets
public_folder: /assets

collections:
  # Blog Post Types
  # Monumenti
  - name: "monumenti"
    label: "Monumenti"
    folder: "content/monuments"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
     preview: false
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "monumenti"}
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Data di pubblicazione", name: "date", widget: "datetime" }
      - { label: "Descrizione", name: "description", widget: "string" }
      - { label: "Categoria",
          name: "category",
          widget: "string",
          default: "monumenti"
        }
      - {label: "In Evidenza", name: "featured", widget: "boolean", default: false}
      - { label: "Thumbnail",
          name: "image",
          widget: "image"
        }
      - { label: "Indirizzo", name: "place", widget: "string" }
      - { label: "Orario", name: "access", widget: "string" }
      - { label: "Info Biglietti", name: "ticket", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Gallery",
          name: "gallery",
          widget: "list",
          fields:
            [
              { label: "Foto", name: "image", widget: "image" },
              { label: "Descrizione Foto", name: "alt", widget: "string" },
            ],
        }
  # Monuments (English)
  - name: "monuments"
    label: "Monuments"
    folder: "content/en-monuments"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
     preview: false
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "monuments"}
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Published", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Category",
          name: "category",
          widget: "string",
          default: "monumenti"
        }
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - { label: "Thumbnail",
          name: "image",
          widget: "image"
        }
      - { label: "Address", name: "place", widget: "string" }
      - { label: "Opening", name: "access", widget: "string" }
      - { label: "Tickets", name: "ticket", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Gallery",
          name: "gallery",
          widget: "list",
          fields:
            [
              { label: "Image", name: "image", widget: "image" },
              { label: "Image Description", name: "alt", widget: "string" },
            ],
        }
  # Eventi (Italiano)
  - name: "eventi"
    label: "Eventi"
    folder: "content/events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
     preview: false
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "eventi"}
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Data di pubblicazione", name: "date", widget: "datetime" }
      - { label: "Data di inizio evento", name: "start", widget: "datetime" }
      - { label: "Data di fine evento", name: "end", widget: "datetime" }
      - { label: "Descrizione", name: "description", widget: "string" }
      - { label: "Categoria",
          name: "category",
          widget: "string",
          default: "eventi"
        }
      - {label: "In Evidenza", name: "featured", widget: "boolean", default: false}
      - { label: "Thumbnail",
          name: "image",
          widget: "image"
        }
      - { label: "Luogo Evento", name: "place", widget: "string" }
      - { label: "Orario", name: "access", widget: "string" }
      - { label: "Info Biglietti", name: "ticket", widget: "string" }
      - { label: "Tipologia Evento", name: "type", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Gallery",
          name: "gallery",
          widget: "list",
          fields:
            [
              { label: "Foto", name: "image", widget: "image" },
              { label: "Descrizione Foto", name: "alt", widget: "string" },
            ],
        }
  # Events (English)
  - name: "events"
    label: "Events"
    folder: "content/en-events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
     preview: false
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "events"}
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Published", name: "date", widget: "datetime" }
      - { label: "Starting Date", name: "start", widget: "datetime" }
      - { label: "Ending Date", name: "end", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Category",
          name: "category",
          widget: "string",
          default: "eventi"
        }
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - { label: "Thumbnail",
          name: "image",
          widget: "image"
        }
      - { label: "Place", name: "place", widget: "string" }
      - { label: "Opening", name: "access", widget: "string" }
      - { label: "Tickets", name: "ticket", widget: "string" }
      - { label: "Event Type", name: "type", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Gallery",
          name: "gallery",
          widget: "list",
          fields:
            [
              { label: "Image", name: "image", widget: "image" },
              { label: "Image Description", name: "alt", widget: "string" },
            ],
        }
  # Pages
  - name: "pages"
    label: "Pages"
    files:
      # Museum Page
      - file: "content/pages/museum/index.md"
        label: "Museo"
        name: "museum"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "museum"}
          - {label: Titolo, name: title, widget: string}
          - {
              label: "Italiano",
              name: "it",
              widget: "object",
              fields:
                [
                  {label: "Titolo", name: "title", widget: "string"},
                  {label: "Descrizione", name: "description", widget: "string"},
                  {label: "Text A", name: "textA", widget: "string"},
                  {label: "Text B", name: "textB", widget: "string"},
                  {label: "Text C", name: "textC", widget: "string"},
                ],
            }
          - {
              label: "English",
              name: "en",
              widget: "object",
              fields:
                [
                  {label: "Title", name: "title", widget: "string"},
                  {label: "Description", name: "description", widget: "string"},
                  {label: "Text A", name: "textA", widget: "string"},
                  {label: "Text B", name: "textB", widget: "string"},
                  {label: "Text C", name: "textC", widget: "string"},
                ],
            }